BEGIN
;

DROP TABLE IF EXISTS MEMBER_LOGIN
;
DROP TABLE IF EXISTS MEMBER
;
DROP TABLE IF EXISTS CREDIT_TYPE
;
DROP TABLE IF EXISTS FLIGHT_MASTER
 ;
DROP TABLE IF EXISTS FLIGHT
 ;
DROP TABLE IF EXISTS RESERVE_FLIGHT
 ;
DROP TABLE IF EXISTS RESERVATION
 ;
DROP TABLE IF EXISTS ROUTE
 ;
DROP TABLE IF EXISTS BOARDING_CLASS
 ;
DROP TABLE IF EXISTS PASSENGER
 ;
DROP TABLE IF EXISTS AIRPORT
 ;
DROP TABLE IF EXISTS PLANE
 ;
DROP TABLE IF EXISTS FARE_TYPE
 ;
DROP TABLE IF EXISTS PEAK_TIME
 ;

DROP TABLE IF EXISTS sequence
;
CREATE TABLE sequence (
    name VARCHAR(50) NOT NULL,
    current_value INT NOT NULL,
    increment INT NOT NULL DEFAULT 1,
    PRIMARY KEY (name)
) ENGINE=InnoDB
;

DROP FUNCTION IF EXISTS currval
;

CREATE FUNCTION currval (seq_name VARCHAR(50))
    RETURNS INTEGER
    LANGUAGE SQL
    DETERMINISTIC
    CONTAINS SQL
    SQL SECURITY DEFINER
    COMMENT ''
BEGIN
    DECLARE value INTEGER;
    SET value = 0;
    SELECT current_value INTO value
        FROM sequence
        WHERE name = seq_name;
    RETURN value;
END
;


DROP FUNCTION IF EXISTS setval
;

CREATE FUNCTION setval (seq_name VARCHAR(50), value INTEGER)
    RETURNS INTEGER
    LANGUAGE SQL
    DETERMINISTIC
    CONTAINS SQL
    SQL SECURITY DEFINER
    COMMENT ''
BEGIN
    UPDATE sequence
    SET current_value = value
    WHERE name = seq_name;
    RETURN currval(seq_name);
END
;
DROP FUNCTION IF EXISTS nextval
;
CREATE FUNCTION nextval (seq_name VARCHAR(50))
    RETURNS INTEGER
    LANGUAGE SQL
    DETERMINISTIC
    CONTAINS SQL
    SQL SECURITY DEFINER
    COMMENT ''
BEGIN
    UPDATE sequence
    SET current_value = current_value + increment
    WHERE name = seq_name;
    RETURN currval(seq_name);
END
;

COMMIT
;
